# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: 
baseurl: 
title: Priyanshu Arya
author: Priyanshu Arya
description: Priyanshu Arya | Data Science and Machine Learning enthusiast | Personal blog and resume 
avatar: profile.png
email: priyanshuarya2482000@gmail.com
github: coders-i # username
twitter: Priyans80637948
linkedin: priyanshu-arya-934804169
kaggle: codoes
stackoverflow: priyanshu-arya
disqus: disqus_ZAelu1O3ed
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
